### ISSUE TITLE
代码似乎不完整，可否提供部署说明？

### ISSUE THREAD

**Issue by void285** [YLDJack/CBDB-VisualizationSystem#10]
您好，
代码中似乎没有readme中提到的后端组件，是否未完全开源？另外可否提供部署说明，谢谢！

**Comment by YLDJack** [comment]
不好意思，目前我手中只有前端的代码，后端的部分是另外一位同学负责的，他好像已经找不到了。

**Comment by void285** [comment]
谢谢。
我对react技术不熟悉，不过部署了前端代码，日志显示到后端proxy的地址请求失败，应该就是未部署后端服务导致的了。
请问您现在是否还做项目相关的工作？

**Comment by YLDJack** [comment]
对，因为我们后端部署在阿里云上，后面我的阿里云学生服务器到期了，所以这个项目的一些api接口也失效了。这个项目是我研一带本科生做的毕业设计，他们已经毕业了。现在我已经研二下学期了，目前正在公司实习和准备秋招，所以目前没有太多时间能花在这个项目上。等我工作正式offer下来，应该会有时间，我们可以一起探讨项目。

**Comment by void285** [comment]
好的，朋友介绍我看您这个项目，我之前接触过CBDB，做过一个古籍专词标注的项目(itaolang.com)。后面时间余裕我们可探讨合作类似项目，我可以提供国外的服务器资源。

**Comment by YLDJack** [comment]
好的，希望有机会可以一起合作。
可以的话我们可以加个微信，您可以留个邮箱，我把我的微信号发您，或者您也可以直接发到我在readme中留下的邮箱里。

**Comment by void285** [comment]
已发您邮箱。
